export interface WLASLLessonDef {
  id: string;
  title: string;
  words: string[];
  unlockAfter: string | null;
  category: string;
}

export const WLASL_LESSONS: WLASLLessonDef[] = [
  {
    id: "wlasl-01",
    title: "Everyday Objects",
    words: ["BOOK", "DRINK", "COMPUTER", "BEFORE", "CHAIR"],
    unlockAfter: null,
    category: "Beginner",
  },
  {
    id: "wlasl-02",
    title: "People & Greetings",
    words: ["GO", "CLOTHES", "WHO", "CANDY", "COUSIN"],
    unlockAfter: "wlasl-01",
    category: "Beginner",
  },
  {
    id: "wlasl-03",
    title: "Expressions",
    words: ["DEAF", "FINE", "HELP", "NO", "THIN"],
    unlockAfter: "wlasl-02",
    category: "Beginner",
  },
  {
    id: "wlasl-04",
    title: "Actions & Time",
    words: ["WALK", "YEAR", "YES", "ALL", "BLACK"],
    unlockAfter: "wlasl-03",
    category: "Beginner",
  },
  {
    id: "wlasl-05",
    title: "Feelings & States",
    words: ["COOL", "FINISH", "HOT", "LIKE", "MANY"],
    unlockAfter: "wlasl-04",
    category: "Beginner",
  },
  {
    id: "wlasl-06",
    title: "Family & Home",
    words: ["MOTHER", "NOW", "ORANGE", "TABLE", "THANKSGIVING"],
    unlockAfter: "wlasl-05",
    category: "Intermediate",
  },
  {
    id: "wlasl-07",
    title: "Daily Life",
    words: ["WHAT", "WOMAN", "BED", "BLUE", "BOWLING"],
    unlockAfter: "wlasl-06",
    category: "Intermediate",
  },
  {
    id: "wlasl-08",
    title: "Nature & Animals",
    words: ["CAN", "DOG", "FAMILY", "FISH", "GRADUATE"],
    unlockAfter: "wlasl-07",
    category: "Intermediate",
  },
  {
    id: "wlasl-09",
    title: "Social Words",
    words: ["HAT", "HEARING", "KISS", "LANGUAGE", "LATER"],
    unlockAfter: "wlasl-08",
    category: "Intermediate",
  },
  {
    id: "wlasl-10",
    title: "People & Appearance",
    words: ["MAN", "SHIRT", "STUDY", "TALL", "WHITE"],
    unlockAfter: "wlasl-09",
    category: "Intermediate",
  },
  {
    id: "wlasl-11",
    title: "Situations",
    words: ["WRONG", "ACCIDENT", "APPLE", "BIRD", "CHANGE"],
    unlockAfter: "wlasl-10",
    category: "Intermediate",
  },
  {
    id: "wlasl-12",
    title: "World & Nature",
    words: ["COLOR", "CORN", "COW", "DANCE", "DARK"],
    unlockAfter: "wlasl-11",
    category: "Advanced",
  },
  {
    id: "wlasl-13",
    title: "Actions",
    words: ["DOCTOR", "EAT", "ENJOY", "FORGET", "GIVE"],
    unlockAfter: "wlasl-12",
    category: "Advanced",
  },
  {
    id: "wlasl-14",
    title: "Food & Fun",
    words: ["LAST", "MEET", "PINK", "PIZZA", "PLAY"],
    unlockAfter: "wlasl-13",
    category: "Advanced",
  },
  {
    id: "wlasl-15",
    title: "School & Work",
    words: ["SCHOOL", "SECRETARY", "SHORT", "TIME", "WANT"],
    unlockAfter: "wlasl-14",
    category: "Advanced",
  },
  {
    id: "wlasl-16",
    title: "Sports & Celebrations",
    words: ["WORK", "AFRICA", "BASKETBALL", "BIRTHDAY", "BROWN"],
    unlockAfter: "wlasl-15",
    category: "Advanced",
  },
  {
    id: "wlasl-17",
    title: "Decisions & Places",
    words: ["BUT", "CHEAT", "CITY", "COOK", "DECIDE"],
    unlockAfter: "wlasl-16",
    category: "Expert",
  },
  {
    id: "wlasl-18",
    title: "Needs & Objects",
    words: ["FULL", "HOW", "JACKET", "LETTER", "MEDICINE"],
    unlockAfter: "wlasl-17",
    category: "Expert",
  },
  {
    id: "wlasl-19",
    title: "Actions & Art",
    words: ["NEED", "PAINT", "PAPER", "PULL", "PURPLE"],
    unlockAfter: "wlasl-18",
    category: "Expert",
  },
  {
    id: "wlasl-20",
    title: "Final Challenge",
    words: ["RIGHT", "SAME", "SON", "TELL", "THURSDAY"],
    unlockAfter: "wlasl-19",
    category: "Expert",
  },
];

export function getWLASLLessonById(id: string): WLASLLessonDef | undefined {
  return WLASL_LESSONS.find((l) => l.id === id);
}

export function isWLASLLessonUnlocked(completedLessons: string[], unlockAfter: string | null): boolean {
  return unlockAfter === null || completedLessons.includes(unlockAfter);
}

/** Short one-line tip for each WLASL100 word shown during the lesson */
export const WORD_TIPS: Record<string, string> = {
  BOOK: "Open and close both palms flat, like opening a book.",
  DRINK: "Form a C-hand and move it to your mouth as if drinking.",
  COMPUTER: "Brush the dominant C-hand along the non-dominant forearm.",
  BEFORE: "Hold both flat hands forward, then draw the dominant hand back.",
  CHAIR: "Tap two fingers on two fingers of the other hand.",
  GO: "Point both index fingers and arc them forward together.",
  CLOTHES: "Brush both open hands down the chest twice.",
  WHO: "Circle the index finger around the lips.",
  CANDY: "Twist the index finger against the cheek.",
  COUSIN: "Shake a C-hand near the temple.",
  DEAF: "Touch the ear then bring fingers together near mouth.",
  FINE: "Tap the thumb of an open hand on the chest.",
  HELP: "Lift a thumbs-up with the flat non-dominant hand.",
  NO: "Snap the index and middle fingers down onto the thumb.",
  THIN: "Draw the pinkie finger straight down from chin to waist.",
  WALK: "Alternately bend two flat hands forward, like walking feet.",
  YEAR: "Circle one S-hand around the other S-hand.",
  YES: "Nod a closed fist up and down like a head nodding.",
  ALL: "Sweep the open dominant hand in a circle around the non-dominant palm.",
  BLACK: "Pull the index finger across the forehead left to right.",
  COOL: "Fan the fingers of the dominant hand at the chin.",
  FINISH: "Open both hands and flip them outward quickly.",
  HOT: "Claw hand at mouth, then twist it away.",
  LIKE: "Pinch thumb and middle finger from chest outward.",
  MANY: "Flick both closed fists open repeatedly.",
  MOTHER: "Tap the thumb of an open hand on the chin.",
  NOW: "Bend both Y-hands down quickly.",
  ORANGE: "Squeeze a closed hand near the chin like squeezing an orange.",
  TABLE: "Pat the top of a flat forearm with the other flat hand.",
  THANKSGIVING: "Open hand at chin, arc it forward and down.",
  WHAT: "Brush the index finger across the non-dominant palm downward.",
  WOMAN: "Thumb from chin to chest on an open hand.",
  BED: "Tilt the head to rest on two flat hands.",
  BLUE: "Shake a B-hand at the side.",
  BOWLING: "Swing a curved hand forward as if rolling a ball.",
  CAN: "Move both S-hands downward simultaneously.",
  DOG: "Snap fingers after patting the thigh.",
  FAMILY: "Circle two F-hands outward and bring them together.",
  FISH: "Wiggle the flat dominant hand forward like a swimming fish.",
  GRADUATE: "Circle a G-hand and bring it down onto the non-dominant palm.",
  HAT: "Pat the top of the head twice.",
  HEARING: "Circle the index finger near the mouth.",
  KISS: "Touch fingertips to lips then to the cheek.",
  LANGUAGE: "Wiggle both L-hands apart from center.",
  LATER: "Extend an L-hand and pivot the thumb downward.",
  MAN: "Thumb from forehead to chest on an open hand.",
  SHIRT: "Pinch the shirt fabric on the chest and pull.",
  STUDY: "Wiggle the fingers of the dominant hand toward the non-dominant palm.",
  TALL: "Slide the index finger up the non-dominant flat palm.",
  WHITE: "Pull a curved hand away from the chest.",
  WRONG: "Knock the Y-hand against the chin.",
  ACCIDENT: "Bring both closed fists together with impact.",
  APPLE: "Twist an A-hand knuckle into the cheek.",
  BIRD: "Snap index finger and thumb together at the mouth.",
  CHANGE: "Twist both closed hands in opposite directions.",
  COLOR: "Wiggle the fingers in front of the chin.",
  CORN: "Twist index fingers alternately at the side of the mouth.",
  COW: "Place Y-hands with thumbs on temples and twist out.",
  DANCE: "Swing two fingers over the non-dominant palm.",
  DARK: "Cross both flat hands downward in front of the face.",
  DOCTOR: "Tap the dominant M-hand fingers on the wrist.",
  EAT: "Bring fingertips to the mouth once.",
  ENJOY: "Rub both flat hands in circles on the chest.",
  FORGET: "Swipe an open hand across the forehead and close it.",
  GIVE: "Point flat O-hands toward someone and open them.",
  LAST: "Strike the pinkie with the dominant index finger.",
  MEET: "Both index fingers rise and come together.",
  PINK: "Brush the P-hand middle finger down the chin.",
  PIZZA: "Draw a Z in the air with a P-hand.",
  PLAY: "Shake Y-hands loosely at the sides.",
  SCHOOL: "Clap hands twice with a slight offset.",
  SECRETARY: "Draw U-fingers from the side of the chin to the palm.",
  SHORT: "Bend H-fingers and brush them down past each other.",
  TIME: "Tap the wrist with the index finger.",
  WANT: "Claw both hands and draw them toward the body.",
  WORK: "Tap the dominant S-hand on the non-dominant S-hand.",
  AFRICA: "A-hand circles in front of the face.",
  BASKETBALL: "Mime shooting a basketball with both hands.",
  BIRTHDAY: "Touch elbow then bring the middle finger up to the chin.",
  BROWN: "Slide a B-hand down the cheek.",
  BUT: "Cross index fingers and pull them apart.",
  CHEAT: "Slide the V-hand sideways under the non-dominant hand.",
  CITY: "Touch fingertips, break, rotate and touch again.",
  COOK: "Flip the dominant flat hand over the non-dominant palm.",
  DECIDE: "F-hand moves from forehead down to the non-dominant palm.",
  FULL: "Slide the flat hand across the top of the non-dominant fist.",
  HOW: "Knuckles together, roll hands forward and open.",
  JACKET: "Trace lapels with A-hands downward on the chest.",
  LETTER: "Thumb to mouth, then place it on the non-dominant palm.",
  MEDICINE: "Rock the middle finger in the non-dominant palm.",
  NEED: "Bend and tap the X-hand downward.",
  PAINT: "Brush the fingers up and down on the non-dominant palm.",
  PAPER: "Brush both flat hands together in opposite directions.",
  PULL: "Grab air and pull both curved hands toward the body.",
  PURPLE: "Shake a P-hand to the side.",
  RIGHT: "Tap both index fingers together horizontally.",
  SAME: "Swing both Y-hands together.",
  SON: "Mime rocking a baby, then flat hand to forehead.",
  TELL: "Tap the chin with the index finger and point outward.",
  THURSDAY: "H then S — H-hand then S-hand in sequence.",
};
