"""initial schema

Revision ID: 274ab2620adc
Revises: 
Create Date: 2026-05-02 07:54:51.653093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274ab2620adc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('MILESTONE', 'ACCURACY', 'STREAK', 'DISCOVERY', 'SOCIAL', name='achievementcategory'), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'DIAMOND', name='tierenum'), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_session_date', sa.DateTime(), nullable=True),
    sa.Column('streak_shields', sa.Integer(), nullable=False),
    sa.Column('lora_key', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.Enum('STANDARD', 'PREMIUM', 'ADMIN', name='accounttype'), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('league_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('weekly_xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=50), nullable=False),
    sa.Column('hearts_remaining', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.String(length=50), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('handshape_score', sa.Float(), nullable=False),
    sa.Column('orientation_score', sa.Float(), nullable=False),
    sa.Column('movement_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('coaching_message', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaced_repetition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sign_id', name='uq_sr_user_sign')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    # Seed initial achievements
    op.execute("""
        INSERT INTO achievements (id, name, "desc", hint, category, xp_reward) VALUES 
        ('first_sign', 'First Steps', 'Complete your first sign successfully.', NULL, 'MILESTONE', 50),
        ('100_signs', 'Centurion', 'Complete 100 signs successfully.', NULL, 'MILESTONE', 500),
        ('perfect_lesson', 'Flawless', 'Get a perfect score in a lesson.', NULL, 'ACCURACY', 200),
        ('streak_7', 'Dedicated', 'Achieve a 7-day streak.', NULL, 'STREAK', 300),
        ('try_all_drills', 'Explorer', 'Try every drill type at least once.', NULL, 'DISCOVERY', 250),
        ('join_league', 'Competitor', 'Join your first league.', NULL, 'SOCIAL', 150)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    op.drop_table('spaced_repetition')
    op.drop_table('sign_attempts')
    op.drop_table('notifications')
    op.drop_table('lesson_attempts')
    op.drop_table('league_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('leagues')
    op.drop_table('achievements')
    # ### end Alembic commands ###
