export interface ASLCitizenLessonDef {
  id: string;
  title: string;
  words: string[];
  unlockAfter: string | null;
  category: string;
}

export const ASL_CITIZEN_LESSONS: ASLCitizenLessonDef[] = [
  {
    id: "asl-citizen-01",
    title: "Basic Actions & Animals",
    words: ["DOG", "HURDLE/TRIP", "DEMAND", "BITE", "DARK"],
    unlockAfter: null,
    category: "Beginner",
  },
  {
    id: "asl-citizen-02",
    title: "Daily Routine",
    words: ["BREAKFAST", "MECHANIC", "PARTY", "ROCKINGCHAIR", "DEAF"],
    unlockAfter: "asl-citizen-01",
    category: "Beginner",
  },
  {
    id: "asl-citizen-03",
    title: "Around the Clock",
    words: ["WHATFOR", "DECIDE", "FINE", "NOON", "HALLOWEEN"],
    unlockAfter: "asl-citizen-02",
    category: "Beginner",
  },
  {
    id: "asl-citizen-04",
    title: "Self Care & Travel",
    words: ["DEVELOP", "LUNCH", "EDIT", "SHAVE", "BACKPACK"],
    unlockAfter: "asl-citizen-03",
    category: "Beginner",
  },
  {
    id: "asl-citizen-05",
    title: "Objects & Activities",
    words: ["BEE", "BELT", "PATIENT", "CHRISTMAS", "RIVER"],
    unlockAfter: "asl-citizen-04",
    category: "Beginner",
  },
  {
    id: "asl-citizen-06",
    title: "Going Up",
    words: ["ELEVATOR", "AXE", "BASKETBALL", "MEAT", "FLOAT"],
    unlockAfter: "asl-citizen-05",
    category: "Intermediate",
  },
  {
    id: "asl-citizen-07",
    title: "Medical & Health",
    words: ["MICROSCOPE", "HOSPITAL", "CONFUSED", "CANCER", "DRAG"],
    unlockAfter: "asl-citizen-06",
    category: "Intermediate",
  },
  {
    id: "asl-citizen-08",
    title: "Leisure & Food",
    words: ["MOVIE", "EAT", "RAZOR", "FOREIGNER", "GUESS"],
    unlockAfter: "asl-citizen-07",
    category: "Intermediate",
  },
  {
    id: "asl-citizen-09",
    title: "Home & Finance",
    words: ["MAPLE", "SINK", "SQUEEZE", "LOCK", "DOWNSIZE"],
    unlockAfter: "asl-citizen-08",
    category: "Intermediate",
  },
  {
    id: "asl-citizen-10",
    title: "Social Life",
    words: ["THEY", "JEWELRY", "DINNER", "TWINS", "KNIGHT"],
    unlockAfter: "asl-citizen-09",
    category: "Intermediate",
  },
  {
    id: "asl-citizen-11",
    title: "Feelings & States",
    words: ["OFFEND", "SLIDE", "TRACTOR", "PRESS", "SHOCKED"],
    unlockAfter: "asl-citizen-10",
    category: "Advanced",
  },
  {
    id: "asl-citizen-12",
    title: "Nature & Time",
    words: ["SINCE", "THIRD", "ERUPT", "NIGHT", "ARTICULATESIGN"],
    unlockAfter: "asl-citizen-11",
    category: "Advanced",
  },
  {
    id: "asl-citizen-13",
    title: "Communication",
    words: ["VOICE", "CHEEK", "RECENT", "SKI", "HELICOPTER"],
    unlockAfter: "asl-citizen-12",
    category: "Advanced",
  },
  {
    id: "asl-citizen-14",
    title: "Clothing & Items",
    words: ["SCARF", "CALENDAR", "BANDAGE", "DUCK", "SPECIAL"],
    unlockAfter: "asl-citizen-13",
    category: "Advanced",
  },
  {
    id: "asl-citizen-15",
    title: "Variety & Balance",
    words: ["AUTISM", "CLOSE", "UNDERWEAR", "TYPE", "OTHER"],
    unlockAfter: "asl-citizen-14",
    category: "Advanced",
  },
  {
    id: "asl-citizen-16",
    title: "Activities & Nature",
    words: ["WALK TIGHTROPE CL", "BABY", "CHEESEGRATER", "SHARK", "INTUITIVE"],
    unlockAfter: "asl-citizen-15",
    category: "Expert",
  },
  {
    id: "asl-citizen-17",
    title: "Play & Animals",
    words: ["PEEKABOO", "RHINO", "HOW", "SWEATER", "SWEATPANTS"],
    unlockAfter: "asl-citizen-16",
    category: "Expert",
  },
  {
    id: "asl-citizen-18",
    title: "Food & Feelings",
    words: ["VOMIT", "TOMATO", "MYSELF", "EASY", "LONGLINE"],
    unlockAfter: "asl-citizen-17",
    category: "Expert",
  },
  {
    id: "asl-citizen-19",
    title: "Work & Sports",
    words: ["SCROLLDOWN", "TEACH", "TAIL", "BASEBALLCAP", "UNCLE"],
    unlockAfter: "asl-citizen-18",
    category: "Expert",
  },
  {
    id: "asl-citizen-20",
    title: "Coins & Logic",
    words: ["RABBIT", "PENNY", "COPY", "VLOG", "CATAPULT"],
    unlockAfter: "asl-citizen-19",
    category: "Expert",
  },
];

export function getASLCitizenLessonById(id: string): ASLCitizenLessonDef | undefined {
  return ASL_CITIZEN_LESSONS.find((l) => l.id === id);
}

export function isASLCitizenLessonUnlocked(completedLessons: string[], unlockAfter: string | null): boolean {
  return unlockAfter === null || completedLessons.includes(unlockAfter);
}

/** One-line tips for the ASL Citizen Top-100 signs */
export const ASL_CITIZEN_WORD_TIPS: Record<string, string> = {
  DOG: "Snap fingers twice after patting the side of your thigh.",
  "HURDLE/TRIP": "Place index/middle finger of dominant hand over non-dominant arm in a jumping motion.",
  DEMAND: "Point index finger and slice it down firmly toward non-dominant flat palm.",
  BITE: "Form a curved claw with dominant hand and close it over non-dominant hand.",
  DARK: "Cross both flat hands downward in front of your face.",
  BREAKFAST: "Eat + Morning: Tap fingertips on mouth, then form morning rising arm.",
  MECHANIC: "Interlock fingers of both hands and pivot them back and forth like gears.",
  PARTY: "Swing both Y-hands back and forth in front of chest.",
  ROCKINGCHAIR: "Form two curved hands pointing down and swing them back and forth.",
  DEAF: "Touch index finger from ear to corner of mouth.",
  WHATFOR: "Wiggle index finger of dominant hand near temple like thinking.",
  DECIDE: "Touch index finger to temple, then drop both F-hands downward.",
  FINE: "Tap the thumb of your open hand on your chest twice.",
  NOON: "Rest dominant arm straight up on back of flat non-dominant hand.",
  HALLOWEEN: "Cover eyes with curved hands, then pull them away like a mask.",
  DEVELOP: "Slide dominant flat hand up the edge of non-dominant flat hand in stages.",
  LUNCH: "Eat + Noon: Tap fingertips on mouth, then rest dominant arm straight up.",
  EDIT: "Mime cutting or trimming with index and middle fingers on non-dominant hand.",
  SHAVE: "Scrape knuckle of dominant index finger down your cheek.",
  BACKPACK: "Tap shoulders with curved fingers like putting on straps.",
  BEE: "Tap cheek with index finger, then brush it away like swatting a bug.",
  BELT: "Trace a belt around your waist with H-hands meeting at the center.",
  PATIENT: "Draw index finger down your chin slowly.",
  CHRISTMAS: "Form a C-hand and swing it upward in a small arc.",
  RIVER: "Move both open hands forward in a wavy water-like motion.",
  ELEVATOR: "Move an E-hand up and down along the side of the other flat hand.",
  AXE: "Mime chopping wood with both hands clasped together.",
  BASKETBALL: "Hold both hands up and mime shooting a basketball.",
  MEAT: "Pinch the fleshy part of your non-dominant hand with dominant hand.",
  FLOAT: "Place curved dominant hand on top of flat non-dominant hand and rock it.",
  MICROSCOPE: "Look through your dominant fist at your non-dominant palm.",
  HOSPITAL: "Draw a small cross on your non-dominant shoulder using H-hand.",
  CONFUSED: "Hold curved hands near forehead and cycle them in opposite circles.",
  CANCER: "Form a claw with dominant hand and walk it slowly over non-dominant arm.",
  DRAG: "Pull your dominant hand backward as if hauling a heavy object.",
  MOVIE: "Wiggle dominant hand flat against non-dominant flat palm.",
  EAT: "Bring dominant fingertips to the mouth once.",
  RAZOR: "Mime shaving your cheek with the edge of a thumb.",
  FOREIGNER: "Point index finger and circle it outward from temple.",
  GUESS: "Swipe dominant hand across forehead in a grabbing motion.",
  MAPLE: "Form a leaf shape with your fingers spreading out from palms.",
  SINK: "Mime washing your hands under a flowing faucet.",
  SQUEEZE: "Squeeze both fists tightly twice.",
  LOCK: "Turn your dominant key-hand over your non-dominant fist.",
  DOWNSIZE: "Bring flat palms closer together horizontally.",
  THEY: "Point index finger and sweep it in an arc toward a group.",
  JEWELRY: "Point to throat, wrists, and ears to indicate accessories.",
  DINNER: "Eat + Night: Tap fingertips on mouth, then rest dominant curved hand on wrist.",
  TWINS: "Tap T-hand on left side of chin then right side.",
  KNIGHT: "Form a helmet visor sweep with dominant hand over face.",
  OFFEND: "Flick dominant index finger forward from throat.",
  SLIDE: "Slide dominant flat hand down the palm of non-dominant flat hand.",
  TRACTOR: "Mime holding a steering wheel and vibrating up and down.",
  PRESS: "Push dominant thumb down into non-dominant flat palm.",
  SHOCKED: "Hold claws near face and open eyes wide.",
  SINCE: "Point index fingers at shoulders, then draw them forward and down.",
  THIRD: "Hold up three fingers (thumb, index, middle) and twist hand.",
  ERUPT: "Form a volcano shape with both hands, then explode them upward.",
  NIGHT: "Rest dominant curved hand over non-dominant flat hand.",
  ARTICULATESIGN: "Move both flat hands from mouth outward in a smooth signing motion.",
  VOICE: "Draw V-hand upward along throat.",
  CHEEK: "Pinch cheek with index and thumb.",
  RECENT: "Shake curved index finger back over shoulder twice.",
  SKI: "Mime ski poles pushing backward with both fists.",
  HELICOPTER: "Place dominant open palm on top of non-dominant index finger and flutter.",
  SCARF: "Mime wrapping a scarf around your neck with both hands.",
  CALENDAR: "Slide flat hand down non-dominant flat palm like reading columns.",
  BANDAGE: "Swipe index/middle fingers over back of other wrist.",
  DUCK: "Open and close index and middle fingers against thumb at mouth like a beak.",
  SPECIAL: "Grab dominant index finger with non-dominant hand and pull upward.",
  AUTISM: "Hold dominant hand near forehead and wiggle fingers outwards.",
  CLOSE: "Bring both flat hands together from sides.",
  UNDERWEAR: "Trace waistline with index and thumb of both hands.",
  TYPE: "Mime typing on an invisible keyboard.",
  OTHER: "Flip dominant A-hand over to point outward to the side.",
  "WALK TIGHTROPE CL": "Index and middle fingers of one hand balance along the edge of the other hand.",
  BABY: "Mime cradling and rocking a baby in your arms.",
  CHEESEGRATER: "Scrape dominant claw hand down non-dominant flat palm twice.",
  SHARK: "Place dominant flat hand on forehead like a shark fin.",
  INTUITIVE: "Tap index finger to head, then flow hands forward in smooth waves.",
  PEEKABOO: "Cover your eyes with both hands, then open them quickly.",
  RHINO: "Place dominant index finger at nose pointing forward like a horn.",
  HOW: "Place knuckles together, roll hands forward and open palms up.",
  SWEATER: "Pull down on your shirt cuffs with both hands.",
  SWEATPANTS: "Trace pants down legs with claw hands.",
  VOMIT: "Bring dominant open hand forward from mouth in an exploding arc.",
  TOMATO: "Index finger of dominant hand slices down non-dominant index finger.",
  MYSELF: "Tap dominant fist against chest twice.",
  EASY: "Brush dominant fingertips upward against non-dominant fingertips twice.",
  LONGLINE: "Draw index fingers apart horizontally from center.",
  SCROLLDOWN: "Mime swiping up or down repeatedly with dominant index finger.",
  TEACH: "Bring both O-hands forward from temples twice.",
  TAIL: "Mime a tail wagging behind you with dominant index finger.",
  BASEBALLCAP: "Tap forehead twice with dominant flat hand to indicate a cap brim.",
  UNCLE: "Shake U-hand twice near temple.",
  RABBIT: "Hold two fingers of both hands near ears and bend them twice.",
  PENNY: "Touch index finger to forehead, then show one finger.",
  COPY: "Pull hand away from non-dominant palm while closing fingers together.",
  VLOG: "Mime holding a camera while signing towards it.",
  CATAPULT: "Flick dominant index/middle fingers forward from thumb.",
};
